In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

print(np.random.randn(5))
print(np.random.normal(0, 1, 5))

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)
print(a * b)
print(a / b)

data = np.array([1, 2, 3, 4, 5])
print(np.mean(data))
print(np.std(data))
print(np.var(data))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[ 2.0789339   0.7937548   0.77857254 -0.04905046  0.00350561]
[ 0.66933271 -1.40591835 -1.65730088  0.62704097 -1.6095907 ]
[11 22 33]
[10 40 90]
[10. 10. 10.]
3.0
1.4142135623730951
2.0
